### ISSUE TITLE
Timeout errors when using middleware

### ISSUE THREAD

**Issue by jakemauer** [adjust/shrimp#3]
Hi there,

I'm attempting to use the Shrimp middleware and I have PhantomJS 1.9 installed on my system, however when I browse to a .pdf URL, the server responds with "Preparing PDF..." and then after my timeout has elapsed, "Sorry, request timed out..."

I'm using foreman with unicorn just in case it was a result of a single threaded server causing issues. It also fails the same way if I use regular Webrick. 

Any ideas what's going on?

Thanks for all your work on Shrimp!

**Comment by omnikron** [comment]
@jakemauer what happens if you visit the same page without the .pdf extension?

**Comment by jakemauer** [comment]
Without the extension the page loads up a-ok. I. Noticed that if I increased the Cache TTL it would work more often, but now I seem to have issues where the PDFs that are generated are always 0 bytes, resulting in 504's.

**Comment by rapimo** [comment]
Do you have any redirects ?

**Comment by jakemauer** [comment]
No, no redirects.

**Comment by rapimo** [comment]
I asume that there is no user authentication or any other security issue in your app
so try

```
Shrimp::Phantom.new(url).to_pdf!(target_path)
```

in your rails console 
Does this work?

**Comment by nathanbrakken** [comment]
I get the same message 

> "Preparing PDF..." and then after my timeout has elapsed, "Sorry, request timed out..."

this works for me:

``` ruby
require 'shrimp'
url     = 'http://google.com'
options = { :margin => "1cm" :}
Shrimp::Phantom.new(url, options).to_pdf("output.pdf")
```

but when I hit my app it does not create a pdf (I think due to ssl errors in my development env).

Is there any way to pass something like 
`--ignore-ssl-errors=[true|false]`

to phantomjs via the middleware or configs passed?

Thanks!

**Comment by rapimo** [comment]
as of #7 you can pass a command line configuration json file

**Comment by elorest** [comment]
I'm also getting this issue. I've tried multiple rails servers and setting the timeouts really high. It still seems to timeout after the same amount of time though. 

```
 Rails.application.config.phantomjs_command_line_options  = "--ignore-ssl-errors=true --web-security=false"
 Rails.application.config.middleware.use Shrimp::Middleware, {phantomjs: '/usr/local/bin/phantomjs', rendering_time: 1000000, rendering_timeout: 9000000}
```
